export const COMPANY = {
  name: "Therklima",
  tagline: "Vos Experts en Électricité, Plomberie, Chauffage, Climatisation, PAC & Ventilation",
  phone: "06 63 75 75 63",
  phoneHref: "tel:+33663757563",
  email: "contact@therklima.com",
  address: "6 Rue d'Armaillé, 75017 Paris",
  addressFull: "6 Rue d'Armaillé, 75017 Paris, France",
  hours: "7j/7 — 24h/24",
  siret: "XXX XXX XXX 00014",
  url: "https://therklima.com",
} as const;

export const METIERS = [
  {
    id: "electricite",
    name: "Électricité",
    slug: "/electricite",
    color: "#ff8c00",
    colorClass: "text-[#ff8c00]",
    bgClass: "bg-[#ff8c00]",
    bgLightClass: "bg-[#fff8ee]",
    borderClass: "border-[#ff8c00]",
    icon: "Zap",
    description: "Installation, rénovation, dépannage électrique",
    prestations: [
      "Installation neuve",
      "Rénovation électrique",
      "Dépannage urgent",
      "Mise en conformité NF C 15-100",
      "Tableau électrique",
      "Domotique & éclairage",
    ],
  },
  {
    id: "plomberie",
    name: "Plomberie",
    slug: "/plomberie",
    color: "#2196f3",
    colorClass: "text-[#2196f3]",
    bgClass: "bg-[#2196f3]",
    bgLightClass: "bg-[#e3f2fd]",
    borderClass: "border-[#2196f3]",
    icon: "Droplets",
    description: "Fuite, sanitaire, chauffe-eau, débouchage",
    prestations: [
      "Installation sanitaire",
      "Rénovation plomberie",
      "Dépannage fuite / WC",
      "Chauffe-eau & ballon",
      "Robinetterie",
      "Débouchage",
    ],
  },
  {
    id: "chauffage",
    name: "Chauffage",
    slug: "/chauffage",
    color: "#f44336",
    colorClass: "text-[#f44336]",
    bgClass: "bg-[#f44336]",
    bgLightClass: "bg-[#ffeaea]",
    borderClass: "border-[#f44336]",
    icon: "Flame",
    description: "Chaudière, radiateurs, plancher chauffant",
    prestations: [
      "Installation chaudière",
      "Rénovation chauffage",
      "Radiateurs & planchers chauffants",
      "Entretien annuel",
      "Dépannage chauffage",
      "Chaudière à condensation",
    ],
  },
  {
    id: "climatisation",
    name: "Climatisation",
    slug: "/climatisation",
    color: "#00bcd4",
    colorClass: "text-[#00bcd4]",
    bgClass: "bg-[#00bcd4]",
    bgLightClass: "bg-[#e0f7fa]",
    borderClass: "border-[#00bcd4]",
    icon: "Snowflake",
    description: "Split mural, gainable, multi-split, entretien",
    prestations: [
      "Installation split mural",
      "Climatisation gainable",
      "Multi-split",
      "Dépannage clim",
      "Entretien & recharge",
      "Climatisation réversible",
    ],
  },
  {
    id: "pac",
    name: "Pompe à Chaleur",
    slug: "/pac",
    color: "#4caf50",
    colorClass: "text-[#4caf50]",
    bgClass: "bg-[#4caf50]",
    bgLightClass: "bg-[#e8f5e9]",
    borderClass: "border-[#4caf50]",
    icon: "Thermometer",
    description: "PAC air-air, air-eau, installation, entretien",
    prestations: [
      "PAC air-air",
      "PAC air-eau",
      "Installation neuve",
      "Remplacement chaudière par PAC",
      "Entretien PAC",
      "PAC géothermique",
    ],
  },
  {
    id: "ventilation",
    name: "Ventilation",
    slug: "/ventilation",
    color: "#9c27b0",
    colorClass: "text-[#9c27b0]",
    bgClass: "bg-[#9c27b0]",
    bgLightClass: "bg-[#f3e5f5]",
    borderClass: "border-[#9c27b0]",
    icon: "Wind",
    description: "VMC simple flux, double flux, entretien",
    prestations: [
      "VMC simple flux",
      "VMC double flux",
      "Installation neuve",
      "Entretien & nettoyage",
      "Dépannage VMC",
      "VMC hygroréglable",
    ],
  },
] as const;

export type MetierId = (typeof METIERS)[number]["id"];
